import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import AntTheme from '@repo/ui/AntTheme';
import { getMessages } from 'next-intl/server';
import { NextIntlClientProvider } from 'next-intl';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: string };
}) {
  const messages = await getMessages();
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <AntTheme>
          <NextIntlClientProvider messages={messages}>
            {children}
          </NextIntlClientProvider>
        </AntTheme>
      </body>
    </html>
  );
}

